apiVersion: v1
kind: Pod
metadata:
  name: keepalived
  namespace: kube-system
spec:
  containers:
    # - image: osixia/keepalived:2.0.17
    - image: osixia/keepalived:stable-arm64v8
      name: keepalived
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - NET_BROADCAST
            - NET_RAW
      volumeMounts:
        - mountPath: /usr/local/etc/keepalived/keepalived.conf
          name: config
        - mountPath: /etc/keepalived/check_apiserver.sh
          name: check
  hostNetwork: true
  volumes:
    - hostPath:
        path: /etc/keepalived/keepalived.conf
      name: config
    - hostPath:
        path: /etc/keepalived/check_apiserver.sh
      name: check
status: {}