controller:
  adminUser: "admin"
  adminPassword: "admin"
  jenkinsUrl: "http://192.168.56.10:80"
  servicePort: 80
  serviceType: LoadBalancer
  healthProbes: false
  nodeSelector:
    kubernetes.io/hostname: "kubernetes-master-node"
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
      operator: Exists
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
      operator: Exists

agent:
  jenkinsUrl: "http://192.168.56.10:80"
#  jenkinsTunnel: "jenkins-agent:50000"
  runAsUser: "1000"
  runAsGroup: "999"
  volumes:
    - type: HostPath
      hostPath: "/usr/bin/kubectl"
      mountPath: "/usr/bin/kubectl"
    - type: HostPath
      hostPath: "/bin/docker"
      mountPath: "/bin/docker"
    - type: HostPath
      hostPath: "/var/run/docker.sock"
      mountPath: "/var/run/docker.sock"

persistence:
  existingClaim: jenkins
