apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.0.0.1:6443
    token: gustjr.qnxmtmxmfoqxhzms
    caCertHashes:
    - sha256:dd4a7ba02f2e68576549452a2d9214afc317f98144988cd0b92963e1261650e1
    unsafeSkipCAVerification: false
  timeout: 40s
  tlsBootstrapToken: gustjr.qnxmtmxmfoqxhzms
caCertPath: /etc/kubernetes/pki/ca.crt
nodeRegistration:
  criSocket: unix:////var/run/containerd/containerd.sock
