# https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
- token: "gustjr.qnxmtmxmfoqxhzms"
  ttl: "1h"
  usages:
  - authentication
  - signing
nodeRegistration:
  criSocket: unix:////var/run/containerd/containerd.sock
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.23.0
controlPlaneEndpoint: 192.168.64.84:6443
clusterName: cluster.local
networking:
  dnsDomain: cluster.local
  serviceSubnet: "10.233.0.0/18"
  podSubnet: "10.233.64.0/18"
# https://coredns.io/
dns:
  imageRepository: registry.k8s.io/coredns
  imageTag: v1.8.6
# https://etcd.io/
etcd:
  local:
    imageRepository: "registry.k8s.io"
    imageTag: "3.5.1-0"
    dataDir: "/var/lib/etcd"
    # https://etcd.io/docs/v3.5/op-guide/configuration/
    # https://etcd.io/docs/v3.4/op-guide/configuration/
    extraArgs:
      wal-dir: /var/lib/etcd/wal
      grpc-keepalive-interval: 1h
      grpc-keepalive-timeout: 30s
apiServer:
  # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
  extraArgs:
    # If true, allow privileged containers. [Default: false]
    allow-privileged: "true"
    # Enables anonymous requests to the secure port of the API server. [Default: true]
    anonymous-auth: "true"
    # Ordered list of plug-ins to do authorization on secure port. [Default: Node,RBAC] 
    authorization-mode: Node,RBAC
    # Turns on aggregator routing requests to endpoints IP rather than cluster IP.
    enable-aggregator-routing: "false"
    # Enable to allow secrets of type 'bootstrap.kubernetes.io/token' in the 'kube-system' namespace
    enable-bootstrap-token-auth: "false"
    # Enable profiling via web interface [Ex: https:/10.10.10.3:6443/debug/pprof/]
    profiling: "true"
    # If true, validate ServiceAccount tokens exist in etcd as part of authentication.
    service-account-lookup: "false"
    # A port range to reserve for services with NodePort visibility
    service-node-port-range: 30000-32767
    # number for the log level verbosity
    v: "5"
  extraVolumes:
  - name: usr-share-ca-certificates
    hostPath: /var/lib/kube-apiserver/ca-cert
    mountPath: /usr/share/ca-certificates
    readOnly: true
  timeoutForControlPlane: 5m0s
controllerManager:
  # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
  extraArgs:
    # The number of garbage collector workers that are allowed to sync concurrently. [Default: 20]
    concurrent-gc-syncs: "40"
    # The number of resource quotas that are allowed to sync concurrently. [Default: 5]
    concurrent-resource-quota-syncs: "10"
    # Enable profiling via web interface [Ex: https:/10.10.10.3:6443/debug/pprof/]
    profiling: "true"
    # number for the log level verbosity
    v: "5"
scheduler:
  # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
  extraArgs:
    v: "5"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
