apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: {{--GLOBAL_SERVER_ENDPOINT--}}
    token: {{--TOKEN--}}
    caCertHashes:
     - {{--CA_CRT_HASH--}}
    unsafeSkipCAVerification: false
  timeout: 40s
  tlsBootstrapToken: {{--TOKEN--}}
caCertPath: /etc/kubernetes/pki/ca.crt
nodeRegistration:
  criSocket: unix:////var/run/containerd/containerd.sock
  taint: []
# controlPlane:
#   certificateKey: {{--CRT_KEY--}}
#   localAPIEndpoint:
#     advertiseAddress: {{--LOCAL_SERVER_IP--}}
#     bindPort: 6443